// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: idl/machine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// length >= 6
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MachineCreateRequest) Reset() {
	*x = MachineCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCreateRequest) ProtoMessage() {}

func (x *MachineCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCreateRequest.ProtoReflect.Descriptor instead.
func (*MachineCreateRequest) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MachineCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *MachineError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *Machine      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MachineCreateReply) Reset() {
	*x = MachineCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCreateReply) ProtoMessage() {}

func (x *MachineCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCreateReply.ProtoReflect.Descriptor instead.
func (*MachineCreateReply) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{1}
}

func (x *MachineCreateReply) GetError() *MachineError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *MachineCreateReply) GetData() *Machine {
	if x != nil {
		return x.Data
	}
	return nil
}

type MachineRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	MachineID int64 `protobuf:"varint,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
}

func (x *MachineRemoveRequest) Reset() {
	*x = MachineRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineRemoveRequest) ProtoMessage() {}

func (x *MachineRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineRemoveRequest.ProtoReflect.Descriptor instead.
func (*MachineRemoveRequest) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{2}
}

func (x *MachineRemoveRequest) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type MachineRemoveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *MachineError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MachineRemoveReply) Reset() {
	*x = MachineRemoveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineRemoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineRemoveReply) ProtoMessage() {}

func (x *MachineRemoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineRemoveReply.ProtoReflect.Descriptor instead.
func (*MachineRemoveReply) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{3}
}

func (x *MachineRemoveReply) GetError() *MachineError {
	if x != nil {
		return x.Error
	}
	return nil
}

type MachineRenameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	MachineID int64  `protobuf:"varint,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MachineRenameRequest) Reset() {
	*x = MachineRenameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineRenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineRenameRequest) ProtoMessage() {}

func (x *MachineRenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineRenameRequest.ProtoReflect.Descriptor instead.
func (*MachineRenameRequest) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{4}
}

func (x *MachineRenameRequest) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *MachineRenameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MachineRenameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *MachineError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MachineRenameReply) Reset() {
	*x = MachineRenameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineRenameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineRenameReply) ProtoMessage() {}

func (x *MachineRenameReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineRenameReply.ProtoReflect.Descriptor instead.
func (*MachineRenameReply) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{5}
}

func (x *MachineRenameReply) GetError() *MachineError {
	if x != nil {
		return x.Error
	}
	return nil
}

type MachineInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	MachineID int64 `protobuf:"varint,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
}

func (x *MachineInfoRequest) Reset() {
	*x = MachineInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfoRequest) ProtoMessage() {}

func (x *MachineInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfoRequest.ProtoReflect.Descriptor instead.
func (*MachineInfoRequest) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{6}
}

func (x *MachineInfoRequest) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type MachineInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *MachineError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *Machine      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MachineInfoReply) Reset() {
	*x = MachineInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfoReply) ProtoMessage() {}

func (x *MachineInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfoReply.ProtoReflect.Descriptor instead.
func (*MachineInfoReply) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{7}
}

func (x *MachineInfoReply) GetError() *MachineError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *MachineInfoReply) GetData() *Machine {
	if x != nil {
		return x.Data
	}
	return nil
}

type MachineListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// default 1
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// default 10
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Key   string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MachineListRequest) Reset() {
	*x = MachineListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineListRequest) ProtoMessage() {}

func (x *MachineListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineListRequest.ProtoReflect.Descriptor instead.
func (*MachineListRequest) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{8}
}

func (x *MachineListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MachineListRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MachineListRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MachineListRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MachineListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *MachineError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  []*Machine    `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Total int64         `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *MachineListReply) Reset() {
	*x = MachineListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineListReply) ProtoMessage() {}

func (x *MachineListReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineListReply.ProtoReflect.Descriptor instead.
func (*MachineListReply) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{9}
}

func (x *MachineListReply) GetError() *MachineError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *MachineListReply) GetData() []*Machine {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MachineListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Machine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineID int64  `protobuf:"varint,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Machine) Reset() {
	*x = Machine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{10}
}

func (x *Machine) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *Machine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MachineError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *MachineError) Reset() {
	*x = MachineError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineError) ProtoMessage() {}

func (x *MachineError) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineError.ProtoReflect.Descriptor instead.
func (*MachineError) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{11}
}

func (x *MachineError) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MachineError) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_idl_machine_proto protoreflect.FileDescriptor

var file_idl_machine_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x64, 0x6c, 0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x73, 0x68, 0x22, 0x2a, 0x0a, 0x14, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73,
	0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x34, 0x0a, 0x14, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x22, 0x3e,
	0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x48,
	0x0a, 0x14, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x32, 0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x22, 0x5f, 0x0a, 0x10,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x66, 0x0a,
	0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x75, 0x0a, 0x10, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x3b, 0x0a, 0x07,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x32, 0xc4, 0x02, 0x0a, 0x0e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1a,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x73,
	0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x1a,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x73,
	0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x06, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x73,
	0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x6d,
	0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_machine_proto_rawDescOnce sync.Once
	file_idl_machine_proto_rawDescData = file_idl_machine_proto_rawDesc
)

func file_idl_machine_proto_rawDescGZIP() []byte {
	file_idl_machine_proto_rawDescOnce.Do(func() {
		file_idl_machine_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_machine_proto_rawDescData)
	})
	return file_idl_machine_proto_rawDescData
}

var file_idl_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_idl_machine_proto_goTypes = []interface{}{
	(*MachineCreateRequest)(nil), // 0: mesh.MachineCreateRequest
	(*MachineCreateReply)(nil),   // 1: mesh.MachineCreateReply
	(*MachineRemoveRequest)(nil), // 2: mesh.MachineRemoveRequest
	(*MachineRemoveReply)(nil),   // 3: mesh.MachineRemoveReply
	(*MachineRenameRequest)(nil), // 4: mesh.MachineRenameRequest
	(*MachineRenameReply)(nil),   // 5: mesh.MachineRenameReply
	(*MachineInfoRequest)(nil),   // 6: mesh.MachineInfoRequest
	(*MachineInfoReply)(nil),     // 7: mesh.MachineInfoReply
	(*MachineListRequest)(nil),   // 8: mesh.MachineListRequest
	(*MachineListReply)(nil),     // 9: mesh.MachineListReply
	(*Machine)(nil),              // 10: mesh.Machine
	(*MachineError)(nil),         // 11: mesh.MachineError
}
var file_idl_machine_proto_depIdxs = []int32{
	11, // 0: mesh.MachineCreateReply.error:type_name -> mesh.MachineError
	10, // 1: mesh.MachineCreateReply.data:type_name -> mesh.Machine
	11, // 2: mesh.MachineRemoveReply.error:type_name -> mesh.MachineError
	11, // 3: mesh.MachineRenameReply.error:type_name -> mesh.MachineError
	11, // 4: mesh.MachineInfoReply.error:type_name -> mesh.MachineError
	10, // 5: mesh.MachineInfoReply.data:type_name -> mesh.Machine
	11, // 6: mesh.MachineListReply.error:type_name -> mesh.MachineError
	10, // 7: mesh.MachineListReply.data:type_name -> mesh.Machine
	0,  // 8: mesh.MachineService.Create:input_type -> mesh.MachineCreateRequest
	2,  // 9: mesh.MachineService.Remove:input_type -> mesh.MachineRemoveRequest
	4,  // 10: mesh.MachineService.Rename:input_type -> mesh.MachineRenameRequest
	6,  // 11: mesh.MachineService.Info:input_type -> mesh.MachineInfoRequest
	8,  // 12: mesh.MachineService.List:input_type -> mesh.MachineListRequest
	1,  // 13: mesh.MachineService.Create:output_type -> mesh.MachineCreateReply
	3,  // 14: mesh.MachineService.Remove:output_type -> mesh.MachineRemoveReply
	5,  // 15: mesh.MachineService.Rename:output_type -> mesh.MachineRenameReply
	7,  // 16: mesh.MachineService.Info:output_type -> mesh.MachineInfoReply
	9,  // 17: mesh.MachineService.List:output_type -> mesh.MachineListReply
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_idl_machine_proto_init() }
func file_idl_machine_proto_init() {
	if File_idl_machine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_machine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineRemoveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineRenameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineRenameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Machine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_machine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_machine_proto_goTypes,
		DependencyIndexes: file_idl_machine_proto_depIdxs,
		MessageInfos:      file_idl_machine_proto_msgTypes,
	}.Build()
	File_idl_machine_proto = out.File
	file_idl_machine_proto_rawDesc = nil
	file_idl_machine_proto_goTypes = nil
	file_idl_machine_proto_depIdxs = nil
}
