// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: idl/machine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineStatus int32

const (
	MachineStatus_MACHINE_UNKNOWN MachineStatus = 0
	MachineStatus_MACHINE_ONLINE  MachineStatus = 1
	MachineStatus_MACHINE_RUNNING MachineStatus = 2
	MachineStatus_MACHINE_OFFLINE MachineStatus = 3
)

// Enum value maps for MachineStatus.
var (
	MachineStatus_name = map[int32]string{
		0: "MACHINE_UNKNOWN",
		1: "MACHINE_ONLINE",
		2: "MACHINE_RUNNING",
		3: "MACHINE_OFFLINE",
	}
	MachineStatus_value = map[string]int32{
		"MACHINE_UNKNOWN": 0,
		"MACHINE_ONLINE":  1,
		"MACHINE_RUNNING": 2,
		"MACHINE_OFFLINE": 3,
	}
)

func (x MachineStatus) Enum() *MachineStatus {
	p := new(MachineStatus)
	*p = x
	return p
}

func (x MachineStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_machine_proto_enumTypes[0].Descriptor()
}

func (MachineStatus) Type() protoreflect.EnumType {
	return &file_idl_machine_proto_enumTypes[0]
}

func (x MachineStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineStatus.Descriptor instead.
func (MachineStatus) EnumDescriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{0}
}

type MachineCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// required
	Workpath string `protobuf:"bytes,2,opt,name=workpath,proto3" json:"workpath,omitempty"`
}

func (x *MachineCreateRequest) Reset() {
	*x = MachineCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCreateRequest) ProtoMessage() {}

func (x *MachineCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCreateRequest.ProtoReflect.Descriptor instead.
func (*MachineCreateRequest) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineCreateRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MachineCreateRequest) GetWorkpath() string {
	if x != nil {
		return x.Workpath
	}
	return ""
}

type MachineCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *MachineError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *Machine      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MachineCreateReply) Reset() {
	*x = MachineCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCreateReply) ProtoMessage() {}

func (x *MachineCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCreateReply.ProtoReflect.Descriptor instead.
func (*MachineCreateReply) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{1}
}

func (x *MachineCreateReply) GetError() *MachineError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *MachineCreateReply) GetData() *Machine {
	if x != nil {
		return x.Data
	}
	return nil
}

type MachineRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	MachineID int64 `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
}

func (x *MachineRemoveRequest) Reset() {
	*x = MachineRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineRemoveRequest) ProtoMessage() {}

func (x *MachineRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineRemoveRequest.ProtoReflect.Descriptor instead.
func (*MachineRemoveRequest) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{2}
}

func (x *MachineRemoveRequest) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type MachineRemoveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *MachineError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MachineRemoveReply) Reset() {
	*x = MachineRemoveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineRemoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineRemoveReply) ProtoMessage() {}

func (x *MachineRemoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineRemoveReply.ProtoReflect.Descriptor instead.
func (*MachineRemoveReply) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{3}
}

func (x *MachineRemoveReply) GetError() *MachineError {
	if x != nil {
		return x.Error
	}
	return nil
}

type MachineChangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	MachineID int64 `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	// required
	Status MachineStatus `protobuf:"varint,2,opt,name=status,proto3,enum=mesh.MachineStatus" json:"status,omitempty"`
}

func (x *MachineChangeRequest) Reset() {
	*x = MachineChangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineChangeRequest) ProtoMessage() {}

func (x *MachineChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineChangeRequest.ProtoReflect.Descriptor instead.
func (*MachineChangeRequest) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{4}
}

func (x *MachineChangeRequest) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *MachineChangeRequest) GetStatus() MachineStatus {
	if x != nil {
		return x.Status
	}
	return MachineStatus_MACHINE_UNKNOWN
}

type MachineChangeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *MachineError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MachineChangeReply) Reset() {
	*x = MachineChangeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineChangeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineChangeReply) ProtoMessage() {}

func (x *MachineChangeReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineChangeReply.ProtoReflect.Descriptor instead.
func (*MachineChangeReply) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{5}
}

func (x *MachineChangeReply) GetError() *MachineError {
	if x != nil {
		return x.Error
	}
	return nil
}

type MachineInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	MachineID int64 `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
}

func (x *MachineInfoRequest) Reset() {
	*x = MachineInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfoRequest) ProtoMessage() {}

func (x *MachineInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfoRequest.ProtoReflect.Descriptor instead.
func (*MachineInfoRequest) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{6}
}

func (x *MachineInfoRequest) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type MachineInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *MachineError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *Machine      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MachineInfoReply) Reset() {
	*x = MachineInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfoReply) ProtoMessage() {}

func (x *MachineInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfoReply.ProtoReflect.Descriptor instead.
func (*MachineInfoReply) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{7}
}

func (x *MachineInfoReply) GetError() *MachineError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *MachineInfoReply) GetData() *Machine {
	if x != nil {
		return x.Data
	}
	return nil
}

type MachineListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// default 1
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// default 10
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Key   string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MachineListRequest) Reset() {
	*x = MachineListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineListRequest) ProtoMessage() {}

func (x *MachineListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineListRequest.ProtoReflect.Descriptor instead.
func (*MachineListRequest) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{8}
}

func (x *MachineListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MachineListRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MachineListRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MachineListRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MachineListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *MachineError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  []*Machine    `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Total int64         `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *MachineListReply) Reset() {
	*x = MachineListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineListReply) ProtoMessage() {}

func (x *MachineListReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineListReply.ProtoReflect.Descriptor instead.
func (*MachineListReply) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{9}
}

func (x *MachineListReply) GetError() *MachineError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *MachineListReply) GetData() []*Machine {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MachineListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Machine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineID  int64         `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	Hostname   string        `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Workpath   string        `protobuf:"bytes,3,opt,name=workpath,proto3" json:"workpath,omitempty"`
	Status     MachineStatus `protobuf:"varint,4,opt,name=status,proto3,enum=mesh.MachineStatus" json:"status,omitempty"`
	StatusName string        `protobuf:"bytes,5,opt,name=statusName,proto3" json:"statusName,omitempty"`
}

func (x *Machine) Reset() {
	*x = Machine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{10}
}

func (x *Machine) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *Machine) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Machine) GetWorkpath() string {
	if x != nil {
		return x.Workpath
	}
	return ""
}

func (x *Machine) GetStatus() MachineStatus {
	if x != nil {
		return x.Status
	}
	return MachineStatus_MACHINE_UNKNOWN
}

func (x *Machine) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

type MachineError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *MachineError) Reset() {
	*x = MachineError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_machine_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineError) ProtoMessage() {}

func (x *MachineError) ProtoReflect() protoreflect.Message {
	mi := &file_idl_machine_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineError.ProtoReflect.Descriptor instead.
func (*MachineError) Descriptor() ([]byte, []int) {
	return file_idl_machine_proto_rawDescGZIP(), []int{11}
}

func (x *MachineError) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MachineError) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_idl_machine_proto protoreflect.FileDescriptor

var file_idl_machine_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x64, 0x6c, 0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x73, 0x68, 0x22, 0x4e, 0x0a, 0x14, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x61, 0x74, 0x68, 0x22, 0x61, 0x0a, 0x12, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x34, 0x0a, 0x14,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x49, 0x44, 0x22, 0x3e, 0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x61, 0x0a, 0x14, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3e, 0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73,
	0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x32, 0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x22, 0x5f, 0x0a, 0x10, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d,
	0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x66, 0x0a, 0x12, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x75, 0x0a, 0x10, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0xac, 0x01, 0x0a, 0x07, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x61, 0x74, 0x68, 0x12, 0x2b, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65,
	0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x2a, 0x62, 0x0a, 0x0d, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e,
	0x45, 0x5f, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x41,
	0x43, 0x48, 0x49, 0x4e, 0x45, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12,
	0x13, 0x0a, 0x0f, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x5f, 0x4f, 0x46, 0x46, 0x4c, 0x49,
	0x4e, 0x45, 0x10, 0x03, 0x32, 0xc4, 0x02, 0x0a, 0x0e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x38, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_machine_proto_rawDescOnce sync.Once
	file_idl_machine_proto_rawDescData = file_idl_machine_proto_rawDesc
)

func file_idl_machine_proto_rawDescGZIP() []byte {
	file_idl_machine_proto_rawDescOnce.Do(func() {
		file_idl_machine_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_machine_proto_rawDescData)
	})
	return file_idl_machine_proto_rawDescData
}

var file_idl_machine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idl_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_idl_machine_proto_goTypes = []interface{}{
	(MachineStatus)(0),           // 0: mesh.MachineStatus
	(*MachineCreateRequest)(nil), // 1: mesh.MachineCreateRequest
	(*MachineCreateReply)(nil),   // 2: mesh.MachineCreateReply
	(*MachineRemoveRequest)(nil), // 3: mesh.MachineRemoveRequest
	(*MachineRemoveReply)(nil),   // 4: mesh.MachineRemoveReply
	(*MachineChangeRequest)(nil), // 5: mesh.MachineChangeRequest
	(*MachineChangeReply)(nil),   // 6: mesh.MachineChangeReply
	(*MachineInfoRequest)(nil),   // 7: mesh.MachineInfoRequest
	(*MachineInfoReply)(nil),     // 8: mesh.MachineInfoReply
	(*MachineListRequest)(nil),   // 9: mesh.MachineListRequest
	(*MachineListReply)(nil),     // 10: mesh.MachineListReply
	(*Machine)(nil),              // 11: mesh.Machine
	(*MachineError)(nil),         // 12: mesh.MachineError
}
var file_idl_machine_proto_depIdxs = []int32{
	12, // 0: mesh.MachineCreateReply.error:type_name -> mesh.MachineError
	11, // 1: mesh.MachineCreateReply.data:type_name -> mesh.Machine
	12, // 2: mesh.MachineRemoveReply.error:type_name -> mesh.MachineError
	0,  // 3: mesh.MachineChangeRequest.status:type_name -> mesh.MachineStatus
	12, // 4: mesh.MachineChangeReply.error:type_name -> mesh.MachineError
	12, // 5: mesh.MachineInfoReply.error:type_name -> mesh.MachineError
	11, // 6: mesh.MachineInfoReply.data:type_name -> mesh.Machine
	12, // 7: mesh.MachineListReply.error:type_name -> mesh.MachineError
	11, // 8: mesh.MachineListReply.data:type_name -> mesh.Machine
	0,  // 9: mesh.Machine.status:type_name -> mesh.MachineStatus
	1,  // 10: mesh.MachineService.Create:input_type -> mesh.MachineCreateRequest
	3,  // 11: mesh.MachineService.Remove:input_type -> mesh.MachineRemoveRequest
	5,  // 12: mesh.MachineService.Change:input_type -> mesh.MachineChangeRequest
	7,  // 13: mesh.MachineService.Info:input_type -> mesh.MachineInfoRequest
	9,  // 14: mesh.MachineService.List:input_type -> mesh.MachineListRequest
	2,  // 15: mesh.MachineService.Create:output_type -> mesh.MachineCreateReply
	4,  // 16: mesh.MachineService.Remove:output_type -> mesh.MachineRemoveReply
	6,  // 17: mesh.MachineService.Change:output_type -> mesh.MachineChangeReply
	8,  // 18: mesh.MachineService.Info:output_type -> mesh.MachineInfoReply
	10, // 19: mesh.MachineService.List:output_type -> mesh.MachineListReply
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_idl_machine_proto_init() }
func file_idl_machine_proto_init() {
	if File_idl_machine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_machine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineRemoveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineChangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineChangeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Machine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_machine_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_machine_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_machine_proto_goTypes,
		DependencyIndexes: file_idl_machine_proto_depIdxs,
		EnumInfos:         file_idl_machine_proto_enumTypes,
		MessageInfos:      file_idl_machine_proto_msgTypes,
	}.Build()
	File_idl_machine_proto = out.File
	file_idl_machine_proto_rawDesc = nil
	file_idl_machine_proto_goTypes = nil
	file_idl_machine_proto_depIdxs = nil
}
