// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: idl/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceStatus int32

const (
	ServiceStatus_SERVICE_UNKNOWN ServiceStatus = 0
	ServiceStatus_SERVICE_DEPLOY  ServiceStatus = 1
	ServiceStatus_SERVICE_START   ServiceStatus = 2
	ServiceStatus_SERVICE_ERROR   ServiceStatus = 3
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "SERVICE_UNKNOWN",
		1: "SERVICE_DEPLOY",
		2: "SERVICE_START",
		3: "SERVICE_ERROR",
	}
	ServiceStatus_value = map[string]int32{
		"SERVICE_UNKNOWN": 0,
		"SERVICE_DEPLOY":  1,
		"SERVICE_START":   2,
		"SERVICE_ERROR":   3,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_service_proto_enumTypes[0].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_idl_service_proto_enumTypes[0]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{0}
}

type ServiceCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	MachineID int64 `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	// required
	Mirror string `protobuf:"bytes,2,opt,name=mirror,proto3" json:"mirror,omitempty"`
	Config string `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Dir    string `protobuf:"bytes,4,opt,name=dir,proto3" json:"dir,omitempty"`
	// required
	Cmd string `protobuf:"bytes,5,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Arg string `protobuf:"bytes,6,opt,name=arg,proto3" json:"arg,omitempty"`
	Env string `protobuf:"bytes,7,opt,name=env,proto3" json:"env,omitempty"`
}

func (x *ServiceCreateRequest) Reset() {
	*x = ServiceCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCreateRequest) ProtoMessage() {}

func (x *ServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceCreateRequest) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *ServiceCreateRequest) GetMirror() string {
	if x != nil {
		return x.Mirror
	}
	return ""
}

func (x *ServiceCreateRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *ServiceCreateRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *ServiceCreateRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ServiceCreateRequest) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *ServiceCreateRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

type ServiceCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ServiceError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *Service      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceCreateReply) Reset() {
	*x = ServiceCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCreateReply) ProtoMessage() {}

func (x *ServiceCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCreateReply.ProtoReflect.Descriptor instead.
func (*ServiceCreateReply) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceCreateReply) GetError() *ServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ServiceCreateReply) GetData() *Service {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	ServiceID int64 `protobuf:"varint,1,opt,name=serviceID,proto3" json:"serviceID,omitempty"`
}

func (x *ServiceRemoveRequest) Reset() {
	*x = ServiceRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRemoveRequest) ProtoMessage() {}

func (x *ServiceRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRemoveRequest.ProtoReflect.Descriptor instead.
func (*ServiceRemoveRequest) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceRemoveRequest) GetServiceID() int64 {
	if x != nil {
		return x.ServiceID
	}
	return 0
}

type ServiceRemoveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ServiceError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ServiceRemoveReply) Reset() {
	*x = ServiceRemoveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRemoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRemoveReply) ProtoMessage() {}

func (x *ServiceRemoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRemoveReply.ProtoReflect.Descriptor instead.
func (*ServiceRemoveReply) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceRemoveReply) GetError() *ServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ServiceInputsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ServiceInputsRequest) Reset() {
	*x = ServiceInputsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInputsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInputsRequest) ProtoMessage() {}

func (x *ServiceInputsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInputsRequest.ProtoReflect.Descriptor instead.
func (*ServiceInputsRequest) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceInputsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ServiceInputsRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ServiceInputsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ServiceError        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  []*ServiceInputsItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceInputsReply) Reset() {
	*x = ServiceInputsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInputsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInputsReply) ProtoMessage() {}

func (x *ServiceInputsReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInputsReply.ProtoReflect.Descriptor instead.
func (*ServiceInputsReply) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceInputsReply) GetError() *ServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ServiceInputsReply) GetData() []*ServiceInputsItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceDeployRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	ServiceID int64 `protobuf:"varint,1,opt,name=serviceID,proto3" json:"serviceID,omitempty"`
}

func (x *ServiceDeployRequest) Reset() {
	*x = ServiceDeployRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDeployRequest) ProtoMessage() {}

func (x *ServiceDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDeployRequest.ProtoReflect.Descriptor instead.
func (*ServiceDeployRequest) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceDeployRequest) GetServiceID() int64 {
	if x != nil {
		return x.ServiceID
	}
	return 0
}

type ServiceDeployReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ServiceError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ServiceDeployReply) Reset() {
	*x = ServiceDeployReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDeployReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDeployReply) ProtoMessage() {}

func (x *ServiceDeployReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDeployReply.ProtoReflect.Descriptor instead.
func (*ServiceDeployReply) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceDeployReply) GetError() *ServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ServiceInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	ServiceID int64 `protobuf:"varint,1,opt,name=serviceID,proto3" json:"serviceID,omitempty"`
}

func (x *ServiceInfoRequest) Reset() {
	*x = ServiceInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoRequest) ProtoMessage() {}

func (x *ServiceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoRequest.ProtoReflect.Descriptor instead.
func (*ServiceInfoRequest) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceInfoRequest) GetServiceID() int64 {
	if x != nil {
		return x.ServiceID
	}
	return 0
}

type ServiceInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ServiceError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *Service      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceInfoReply) Reset() {
	*x = ServiceInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoReply) ProtoMessage() {}

func (x *ServiceInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoReply.ProtoReflect.Descriptor instead.
func (*ServiceInfoReply) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceInfoReply) GetError() *ServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ServiceInfoReply) GetData() *Service {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// default 1
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// default 10
	Count     int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Key       string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value     string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	MachineID int64  `protobuf:"varint,5,opt,name=machineID,proto3" json:"machineID,omitempty"`
}

func (x *ServiceListRequest) Reset() {
	*x = ServiceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceListRequest) ProtoMessage() {}

func (x *ServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceListRequest.ProtoReflect.Descriptor instead.
func (*ServiceListRequest) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ServiceListRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ServiceListRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ServiceListRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ServiceListRequest) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type ServiceListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ServiceError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  []*Service    `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Total int64         `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ServiceListReply) Reset() {
	*x = ServiceListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceListReply) ProtoMessage() {}

func (x *ServiceListReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceListReply.ProtoReflect.Descriptor instead.
func (*ServiceListReply) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceListReply) GetError() *ServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ServiceListReply) GetData() []*Service {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServiceListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ServiceInputsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServiceInputsItem) Reset() {
	*x = ServiceInputsItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInputsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInputsItem) ProtoMessage() {}

func (x *ServiceInputsItem) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInputsItem.ProtoReflect.Descriptor instead.
func (*ServiceInputsItem) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{12}
}

func (x *ServiceInputsItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ServiceInputsItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineID int64         `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	ServiceID int64         `protobuf:"varint,2,opt,name=serviceID,proto3" json:"serviceID,omitempty"`
	Status    ServiceStatus `protobuf:"varint,3,opt,name=status,proto3,enum=mesh.ServiceStatus" json:"status,omitempty"`
	Mirror    string        `protobuf:"bytes,4,opt,name=mirror,proto3" json:"mirror,omitempty"`
	Config    string        `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Dir       string        `protobuf:"bytes,6,opt,name=dir,proto3" json:"dir,omitempty"`
	Cmd       string        `protobuf:"bytes,7,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Arg       string        `protobuf:"bytes,8,opt,name=arg,proto3" json:"arg,omitempty"`
	Env       string        `protobuf:"bytes,9,opt,name=env,proto3" json:"env,omitempty"`
	Machine   *Machine      `protobuf:"bytes,10,opt,name=machine,proto3" json:"machine,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{13}
}

func (x *Service) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *Service) GetServiceID() int64 {
	if x != nil {
		return x.ServiceID
	}
	return 0
}

func (x *Service) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_UNKNOWN
}

func (x *Service) GetMirror() string {
	if x != nil {
		return x.Mirror
	}
	return ""
}

func (x *Service) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Service) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Service) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Service) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *Service) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Service) GetMachine() *Machine {
	if x != nil {
		return x.Machine
	}
	return nil
}

type ServiceError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ServiceError) Reset() {
	*x = ServiceError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceError) ProtoMessage() {}

func (x *ServiceError) ProtoReflect() protoreflect.Message {
	mi := &file_idl_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceError.ProtoReflect.Descriptor instead.
func (*ServiceError) Descriptor() ([]byte, []int) {
	return file_idl_service_proto_rawDescGZIP(), []int{14}
}

func (x *ServiceError) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ServiceError) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_idl_service_proto protoreflect.FileDescriptor

var file_idl_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x64, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x73, 0x68, 0x1a, 0x11, 0x69, 0x64, 0x6c, 0x2f, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a,
	0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x72, 0x67, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x76,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x22, 0x61, 0x0a, 0x12, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x34,
	0x0a, 0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x44, 0x22, 0x3e, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x3e, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x6b, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x34, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x22, 0x3e, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d,
	0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x32, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x22, 0x5f, 0x0a, 0x10, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x84, 0x01, 0x0a,
	0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x49, 0x44, 0x22, 0x75, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x3d, 0x0a, 0x11, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x93, 0x02, 0x0a, 0x07, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63,
	0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x72, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x61, 0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x27, 0x0a, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x22,
	0x36, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x2a, 0x5e, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45, 0x52, 0x56,
	0x49, 0x43, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x10,
	0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41,
	0x52, 0x54, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x32, 0x84, 0x03, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x06, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x06, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x06, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d,
	0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x6d,
	0x65, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_service_proto_rawDescOnce sync.Once
	file_idl_service_proto_rawDescData = file_idl_service_proto_rawDesc
)

func file_idl_service_proto_rawDescGZIP() []byte {
	file_idl_service_proto_rawDescOnce.Do(func() {
		file_idl_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_service_proto_rawDescData)
	})
	return file_idl_service_proto_rawDescData
}

var file_idl_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idl_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_idl_service_proto_goTypes = []interface{}{
	(ServiceStatus)(0),           // 0: mesh.ServiceStatus
	(*ServiceCreateRequest)(nil), // 1: mesh.ServiceCreateRequest
	(*ServiceCreateReply)(nil),   // 2: mesh.ServiceCreateReply
	(*ServiceRemoveRequest)(nil), // 3: mesh.ServiceRemoveRequest
	(*ServiceRemoveReply)(nil),   // 4: mesh.ServiceRemoveReply
	(*ServiceInputsRequest)(nil), // 5: mesh.ServiceInputsRequest
	(*ServiceInputsReply)(nil),   // 6: mesh.ServiceInputsReply
	(*ServiceDeployRequest)(nil), // 7: mesh.ServiceDeployRequest
	(*ServiceDeployReply)(nil),   // 8: mesh.ServiceDeployReply
	(*ServiceInfoRequest)(nil),   // 9: mesh.ServiceInfoRequest
	(*ServiceInfoReply)(nil),     // 10: mesh.ServiceInfoReply
	(*ServiceListRequest)(nil),   // 11: mesh.ServiceListRequest
	(*ServiceListReply)(nil),     // 12: mesh.ServiceListReply
	(*ServiceInputsItem)(nil),    // 13: mesh.ServiceInputsItem
	(*Service)(nil),              // 14: mesh.Service
	(*ServiceError)(nil),         // 15: mesh.ServiceError
	(*Machine)(nil),              // 16: mesh.Machine
}
var file_idl_service_proto_depIdxs = []int32{
	15, // 0: mesh.ServiceCreateReply.error:type_name -> mesh.ServiceError
	14, // 1: mesh.ServiceCreateReply.data:type_name -> mesh.Service
	15, // 2: mesh.ServiceRemoveReply.error:type_name -> mesh.ServiceError
	15, // 3: mesh.ServiceInputsReply.error:type_name -> mesh.ServiceError
	13, // 4: mesh.ServiceInputsReply.data:type_name -> mesh.ServiceInputsItem
	15, // 5: mesh.ServiceDeployReply.error:type_name -> mesh.ServiceError
	15, // 6: mesh.ServiceInfoReply.error:type_name -> mesh.ServiceError
	14, // 7: mesh.ServiceInfoReply.data:type_name -> mesh.Service
	15, // 8: mesh.ServiceListReply.error:type_name -> mesh.ServiceError
	14, // 9: mesh.ServiceListReply.data:type_name -> mesh.Service
	0,  // 10: mesh.Service.status:type_name -> mesh.ServiceStatus
	16, // 11: mesh.Service.machine:type_name -> mesh.Machine
	1,  // 12: mesh.ServiceService.Create:input_type -> mesh.ServiceCreateRequest
	3,  // 13: mesh.ServiceService.Remove:input_type -> mesh.ServiceRemoveRequest
	5,  // 14: mesh.ServiceService.Inputs:input_type -> mesh.ServiceInputsRequest
	7,  // 15: mesh.ServiceService.Deploy:input_type -> mesh.ServiceDeployRequest
	9,  // 16: mesh.ServiceService.Info:input_type -> mesh.ServiceInfoRequest
	11, // 17: mesh.ServiceService.List:input_type -> mesh.ServiceListRequest
	2,  // 18: mesh.ServiceService.Create:output_type -> mesh.ServiceCreateReply
	4,  // 19: mesh.ServiceService.Remove:output_type -> mesh.ServiceRemoveReply
	6,  // 20: mesh.ServiceService.Inputs:output_type -> mesh.ServiceInputsReply
	8,  // 21: mesh.ServiceService.Deploy:output_type -> mesh.ServiceDeployReply
	10, // 22: mesh.ServiceService.Info:output_type -> mesh.ServiceInfoReply
	12, // 23: mesh.ServiceService.List:output_type -> mesh.ServiceListReply
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_idl_service_proto_init() }
func file_idl_service_proto_init() {
	if File_idl_service_proto != nil {
		return
	}
	file_idl_machine_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_idl_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRemoveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInputsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInputsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDeployRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDeployReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInputsItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_service_proto_goTypes,
		DependencyIndexes: file_idl_service_proto_depIdxs,
		EnumInfos:         file_idl_service_proto_enumTypes,
		MessageInfos:      file_idl_service_proto_msgTypes,
	}.Build()
	File_idl_service_proto = out.File
	file_idl_service_proto_rawDesc = nil
	file_idl_service_proto_goTypes = nil
	file_idl_service_proto_depIdxs = nil
}
