product:
  name: vue-element-admin
  repos: https://shylinux.com/x/vue-element-admin
  portal:
    - name: mesh
      title: "matrix mesh"
      redirect: /mesh/machine1/list1
      display: "portal/admin/layout/index.vue"
      views:
        - name: machine
          icon: user
          title: "机器列表1"
          service: mesh.machine
          view:
            - name: machine
              icon: user
              title: "机器列表"
              display: "portal/mesh/views/machine/MachineList.vue"
              service: mesh.machine
            - name: service
              icon: user
              title: "服务列表"
              display: "portal/mesh/views/service/ServiceList.vue"
              service: mesh.service
            - name: list2
              icon: user
              title: "用户列表"
              display: "portal/admin/views/user/UserList.vue"
              service: user
            - name: list3
              icon: user
              title: "空间列表"
              display: "portal/admin/views/space/SpaceList.vue"
              service: space
        - name: machine2
          icon: user
          title: "机器列表2"
          service: machine
          view:
            - name: list1
              icon: user
              title: "机器列表1"
              display: "portal/mesh/views/machine/MachineList.vue"
            - name: list2
              icon: user
              title: "机器列表2"
              display: "portal/mesh/views/machine/MachineList.vue"
            - name: list3
              icon: user
              title: "机器列表3"
              display: "portal/mesh/views/machine/MachineList.vue"
