log:
  path: log/service.log
consul:
  addr: ":8500"
  interval: "10s"
service:
  type: "grpc"
  name: "demo"
  port: 9090
internal:
  user:
    target: "demo"
    export: true
  space:
    target: "demo"
    export: true
storage:
  queue:
    name: "pulsar"
    host: 127.0.0.1
    port: 6650
  cache:
    name: "redis"
    password: demo
    host: 127.0.0.1
    port: 6379
  engine:
    name: "mysql"
    username: demo
    password: demo
    database: space
    host: 127.0.0.1
    port: 3306
