logs:
  pid: log/service.pid
  path: log/service.log
  maxsize: 10 # 10M
  maxage: 30  # 30days
  stdout: false
proxy:
  export: true
  simple: false
  local: true
  target: http://localhost:8082
  root: "usr/vue-element-admin/dist/"
  port: 8081
token:
  issuer: "auth"
  secret: "auth"
  expire: "72h"
consul:
  enable: false
  addr: ":8500"
  interval: 10s
server:
  port: 9090
consumer:
  user:
    enable: true
internal:
  auth:
    export: true
    port: 9091
  user:
    export: true
    port: 9092
  mesh:
    export: true
    port: 9093
  space:
    export: true
    port: 9094
engine:
  queue:
    enable: true
    name: pulsar
    host: 127.0.0.1
    port: 6650
  cache:
    enable: true
    name: redis
    host: 127.0.0.1
    port: 6379
  search:
    enable: true
    name: elasticsearch
    index: demo
    host: 127.0.0.1
    port: 9200
  storage:
    type: sqlite
    username: demo
    password: demo
    database: demo
    host: 127.0.0.1
    port: 3306
