consul:
  addr: ":8500"
  interval: "1s"
service:
  name: "demo"
  port: 8083
storage:
  cache:
    password: demo
    host: 127.0.0.1
    port: 10001
  engine:
    username: demo
    password: demo
    database: space
    host: 127.0.0.1
    port: 3306
