logs:
  pid: log/service.pid
  path: log/service.log
  maxsize: 10 # 10M
  maxage: 30  # 30days
  stdout: true
consul:
  addr: ":8500"
  interval: 10s
  workid: 1
server:
  name: demo
  port: 9090
internal:
  auth:
    export: true
    port: 9091
  user:
    export: true
    port: 9092
  space:
    export: true
    port: 9093
engine:
  queue:
    name: pulsar
    host: 127.0.0.1
    port: 6650
  storage:
    name: mysql
    username: demo
    password: demo
    database: demo
    host: 127.0.0.1
    port: 3306
