logs:
  pid: log/service.pid
  path: log/service.log
  maxsize: 10 # 10M
  maxage: 30  # 30days
proxy:
  export: true
  simple: false
  root: "usr/vue-element-admin/dist/"
  port: 8081
token:
  issuer: "auth"
  secret: "auth"
  expire: "72h"
consul:
  enable: true
  addr: ":8500"
  interval: 10s
server:
  port: 9091
engine:
  queue:
    enable: true
    type: pulsar
    host: 127.0.0.1
    port: 6650
  cache:
    enable: true
    type: redis
    host: 127.0.0.1
    port: 6379
  search:
    enable: true
    type: elasticsearch
    index: demo
    host: 127.0.0.1
    port: 9200
  storage:
    type: sqlite
    username: demo
    password: demo
    database: demo
    host: 127.0.0.1
    port: 3306
