logs:
  pid: log/service.pid
  path: log/service.log
  maxsize: 10 # 10M
  maxage: 30  # 30days
proxy:
  export: true
  target: http://localhost:8080
  port: 8081
token:
  issuer: "auth"
  secret: "auth"
  expire: "72h"
server:
  port: 9090
internal:
  auth:
    export: true
  user:
    export: true
  mesh:
    export: true
  space:
    export: true
engine:
  storage:
    name: sqlite
    database: demo

